### ISSUE TITLE
Error when install chat gpt module

### ISSUE THREAD

**Issue by 0xdanieltran** [moon21247/chat-gpt#1]
./node_modules/chatgpt-official/dist/classes/openai.js 8:4
Module parse failed: Unexpected token (8:4)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import { randomUUID } from "crypto";
| class OpenAI {
>   db;
|   options;
|   onUsage;

Please check this error and if anyone know about this error, please help me with this first integration.

**Comment by SuperSmile0109** [comment]
Chat gpt module is for the backend such like python and node.js
If you run this module in the backend, It will be working perfect.

**Comment by 0xdanieltran** [comment]
thanks. let me check

**Comment by SuperSmile0109** [comment]
Welcome

**Comment by 0xdanieltran** [comment]
wow ~ it's working fine.
Thanks very much.
